name: Regression Test Suite

on:
  pull_request:
    types: [opened, synchronize, reopened] # Triggers on PR open, push to PR branch, or PR reopen
jobs:
  # STAGE 1: Running unit tests for fast feedback
  unit_tests:
    name: Unit Tests Regression
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Run Unit Tests (tagged for regression)
        run: npm run test:unit -- --json --outputFile=./reports/jest-results.json || true
      - name: Upload Reports and Check Outcome
        uses: ./.github/actions/report-artifacts
        with:
          html-report-path: ./reports/html
          coverage-report-path: ./reports/coverage/lcov-report
          test-step-id: jest_tests
          html-artifact-name: unit-jest-html-report
          test-results-json-path: ./reports/jest-results.json
  # STAGE 1: Running a subset of critical integration and e2e tests
  critical:
    name: Critical Tests Regression
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Run Critical Tests
        run: npm run test:integration #TODO: add here critical instead of all integration
      - name: Upload Reports and Check Outcome
        uses: ./.github/actions/report-artifacts
        with:
          html-report-path: ./reports/html
          coverage-report-path: ./reports/coverage/lcov-report
          test-step-id: jest_tests_critical
          html-artifact-name: critical-jest-html-report
          test-results-json-path: ./reports/jest-results.json